# Generated by Django 4.0.6 on 2022-08-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
