# Generated by Django 4.0.6 on 2022-07-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(default='', max_length=20, verbose_name='생년월일'),
        ),
    ]
